spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2.console.enabled: true
  datasource:
    url: jdbc:postgresql://ec2-107-20-24-247.compute-1.amazonaws.com:5432/d317c71nlnehi1
    username: zhsalsmwvmfsbp
    password: e3d4f3b5ed1184c49e3e1f128f776ae0c5241a1daf2857936201b358bd820e56
    driverClassName: org.postgresql.Driver
 